app:
    resource: '@AppBundle/Controller/'
    type: annotation
shop:
    resource: '@ShopBundle/Controller/'
    type: annotation
cms:
    resource: "@CmsBundle/Controller/"
    type:     annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
fos_user_registration_register:
    path:      /account/register
    defaults:  { _controller: FOSUserBundle:Registration:register }
elfinder:
     resource: "@FMElfinderBundle/Resources/config/routing.yml"
route:
    resource: "@RouteBundle/Controller/"
    type:     annotation