# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value


services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
    app.form.registration:
        class: UserBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }    
    app.file_uploader:
        class: AppBundle\FileUploader
        arguments: ['%root_directory%']
    app.image_functions:
        class: AppBundle\ImageFunctions
        arguments: ['%root_directory%', '@app.misc_functions']
    app.misc_functions:
        class: AppBundle\MiscFunctions
    app.vend:
        class: ShopBundle\Vend
        arguments: [ "@doctrine.orm.entity_manager" ]
    twig.extension:
        class: ShopBundle\Extensions\TwigExtensions
        arguments: 
            doctrine : '@doctrine'
        tags:
          -  { name: twig.extension }        